version: '3.2'

services:
  sqldata:
      image: mcr.microsoft.com/mssql/server:2022-latest
      container_name: MsSqlServer
      environment:
        - MSSQL_SA_PASSWORD=StrongPassword123!
        - ACCEPT_EULA=Y
      ports:
        - "1433:1433"
      volumes:
        - type: volume
          source: mssql-server-data
          target: /var/opt/mssql

volumes: 
  mssql-server-data:
